# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage, QIcon
import cv2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 476)
        icon = QIcon()
        icon.addPixmap(QPixmap('./icon/icon.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(30, 20, 320, 240))
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(380, 300, 541, 111))
        self.groupBox.setObjectName("groupBox")
        self.scene_select = QtWidgets.QComboBox(self.groupBox)
        self.scene_select.setGeometry(QtCore.QRect(80, 50, 180, 22))
        self.scene_select.setObjectName("scene_select")
        self.scene_select.addItem("")
        self.scene_select.addItem("")
        self.scene_select.addItem("")
        self.scene_select.addItem("")
        self.scene_select.addItem("")
        self.scene_select.addItem("")
        self.scene_text = QtWidgets.QLabel(self.groupBox)
        self.scene_text.setGeometry(QtCore.QRect(20, 50, 60, 22))
        self.scene_text.setObjectName("scene_text")
        self.show_skeleton = QtWidgets.QCheckBox(self.groupBox)
        self.show_skeleton.setGeometry(QtCore.QRect(300, 50, 90, 18))
        self.show_skeleton.setObjectName("show_skeleton")
        self.show_box = QtWidgets.QCheckBox(self.groupBox)
        self.show_box.setGeometry(QtCore.QRect(420, 50, 90, 18))
        self.show_box.setObjectName("show_box")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(126, 270, 128, 128))
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        pixmap = QPixmap('./icon/status_3.png')
        self.icon.setPixmap(pixmap)
        self.icon_text = QtWidgets.QLabel(self.centralwidget)
        self.icon_text.setGeometry(QtCore.QRect(126, 410, 128, 23))
        self.icon_text.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_text.setObjectName("icon_text")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 20, 541, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.left_pose = QtWidgets.QLabel(self.layoutWidget)
        self.left_pose.setObjectName("left_pose")
        self.gridLayout.addWidget(self.left_pose, 0, 1, 1, 1)
        self.right_pose = QtWidgets.QLabel(self.layoutWidget)
        self.right_pose.setObjectName("right_pose")
        self.gridLayout.addWidget(self.right_pose, 0, 3, 1, 1)
        self.duijie_text = QtWidgets.QLabel(self.layoutWidget)
        self.duijie_text.setObjectName("duijie_text")
        self.gridLayout.addWidget(self.duijie_text, 1, 0, 1, 1)
        self.duijie_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.duijie_lbar.setProperty("value", 0)
        self.duijie_lbar.setTextVisible(False)
        self.duijie_lbar.setObjectName("duijie_lbar")
        self.gridLayout.addWidget(self.duijie_lbar, 1, 1, 1, 1)
        self.duijie_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.duijie_lnum.setProperty("value", 0.00)
        self.duijie_lnum.setObjectName("duijie_lnum")
        self.gridLayout.addWidget(self.duijie_lnum, 1, 2, 1, 1)
        self.duijie_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.duijie_rbar.setProperty("value", 0)
        self.duijie_rbar.setTextVisible(False)
        self.duijie_rbar.setObjectName("duijie_rbar")
        self.gridLayout.addWidget(self.duijie_rbar, 1, 3, 1, 1)
        self.duijie_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.duijie_rnum.setProperty("value", 0.00)
        self.duijie_rnum.setObjectName("duijie_rnum")
        self.gridLayout.addWidget(self.duijie_rnum, 1, 4, 1, 1)
        self.fuzhe_text = QtWidgets.QLabel(self.layoutWidget)
        self.fuzhe_text.setObjectName("fuzhe_text")
        self.gridLayout.addWidget(self.fuzhe_text, 2, 0, 1, 1)
        self.fuzhe_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.fuzhe_lbar.setProperty("value", 0)
        self.fuzhe_lbar.setTextVisible(False)
        self.fuzhe_lbar.setObjectName("fuzhe_lbar")
        self.gridLayout.addWidget(self.fuzhe_lbar, 2, 1, 1, 1)
        self.fuzhe_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.fuzhe_lnum.setProperty("value", 0.00)
        self.fuzhe_lnum.setObjectName("fuzhe_lnum")
        self.gridLayout.addWidget(self.fuzhe_lnum, 2, 2, 1, 1)
        self.fuzhe_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.fuzhe_rbar.setProperty("value", 0)
        self.fuzhe_rbar.setTextVisible(False)
        self.fuzhe_rbar.setObjectName("fuzhe_rbar")
        self.gridLayout.addWidget(self.fuzhe_rbar, 2, 3, 1, 1)
        self.fuzhe_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.fuzhe_rnum.setProperty("value", 0.00)
        self.fuzhe_rnum.setObjectName("fuzhe_rnum")
        self.gridLayout.addWidget(self.fuzhe_rnum, 2, 4, 1, 1)
        self.yyq_chuizhi_text = QtWidgets.QLabel(self.layoutWidget)
        self.yyq_chuizhi_text.setObjectName("yyq_chuizhi_text")
        self.gridLayout.addWidget(self.yyq_chuizhi_text, 3, 0, 1, 1)
        self.yyq_chuizhi_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.yyq_chuizhi_lbar.setProperty("value", 0)
        self.yyq_chuizhi_lbar.setTextVisible(False)
        self.yyq_chuizhi_lbar.setObjectName("yyq_chuizhi_lbar")
        self.gridLayout.addWidget(self.yyq_chuizhi_lbar, 3, 1, 1, 1)
        self.yyq_chuizhi_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.yyq_chuizhi_lnum.setProperty("value", 0.00)
        self.yyq_chuizhi_lnum.setObjectName("yyq_chuizhi_lnum")
        self.gridLayout.addWidget(self.yyq_chuizhi_lnum, 3, 2, 1, 1)
        self.yyq_chuizhi_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.yyq_chuizhi_rbar.setProperty("value", 0)
        self.yyq_chuizhi_rbar.setTextVisible(False)
        self.yyq_chuizhi_rbar.setObjectName("yyq_chuizhi_rbar")
        self.gridLayout.addWidget(self.yyq_chuizhi_rbar, 3, 3, 1, 1)
        self.yyq_chuizhi_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.yyq_chuizhi_rnum.setProperty("value", 0.00)
        self.yyq_chuizhi_rnum.setObjectName("yyq_chuizhi_rnum")
        self.gridLayout.addWidget(self.yyq_chuizhi_rnum, 3, 4, 1, 1)
        self.yyq_qingxie_text = QtWidgets.QLabel(self.layoutWidget)
        self.yyq_qingxie_text.setObjectName("yyq_qingxie_text")
        self.gridLayout.addWidget(self.yyq_qingxie_text, 4, 0, 1, 1)
        self.yyq_qingxie_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.yyq_qingxie_lbar.setProperty("value", 0)
        self.yyq_qingxie_lbar.setTextVisible(False)
        self.yyq_qingxie_lbar.setObjectName("yyq_qingxie_lbar")
        self.gridLayout.addWidget(self.yyq_qingxie_lbar, 4, 1, 1, 1)
        self.yyq_qingxie_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.yyq_qingxie_lnum.setProperty("value", 0.00)
        self.yyq_qingxie_lnum.setObjectName("yyq_qingxie_lnum")
        self.gridLayout.addWidget(self.yyq_qingxie_lnum, 4, 2, 1, 1)
        self.yyq_qingxie_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.yyq_qingxie_rbar.setProperty("value", 0)
        self.yyq_qingxie_rbar.setTextVisible(False)
        self.yyq_qingxie_rbar.setObjectName("yyq_qingxie_rbar")
        self.gridLayout.addWidget(self.yyq_qingxie_rbar, 4, 3, 1, 1)
        self.yyq_qingxie_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.yyq_qingxie_rnum.setProperty("value", 0.00)
        self.yyq_qingxie_rnum.setObjectName("yyq_qingxie_rnum")
        self.gridLayout.addWidget(self.yyq_qingxie_rnum, 4, 4, 1, 1)
        self.jq_sizhi_text = QtWidgets.QLabel(self.layoutWidget)
        self.jq_sizhi_text.setObjectName("jq_sizhi_text")
        self.gridLayout.addWidget(self.jq_sizhi_text, 5, 0, 1, 1)
        self.jq_sizhi_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.jq_sizhi_lbar.setProperty("value", 0)
        self.jq_sizhi_lbar.setTextVisible(False)
        self.jq_sizhi_lbar.setObjectName("jq_sizhi_lbar")
        self.gridLayout.addWidget(self.jq_sizhi_lbar, 5, 1, 1, 1)
        self.jq_sizhi_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.jq_sizhi_lnum.setProperty("value", 0.00)
        self.jq_sizhi_lnum.setObjectName("jq_sizhi_lnum")
        self.gridLayout.addWidget(self.jq_sizhi_lnum, 5, 2, 1, 1)
        self.jq_sizhi_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.jq_sizhi_rbar.setProperty("value", 0)
        self.jq_sizhi_rbar.setTextVisible(False)
        self.jq_sizhi_rbar.setObjectName("jq_sizhi_rbar")
        self.gridLayout.addWidget(self.jq_sizhi_rbar, 5, 3, 1, 1)
        self.jq_sizhi_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.jq_sizhi_rnum.setProperty("value", 0.00)
        self.jq_sizhi_rnum.setObjectName("jq_sizhi_rnum")
        self.gridLayout.addWidget(self.jq_sizhi_rnum, 5, 4, 1, 1)
        self.jq_danzhi_text = QtWidgets.QLabel(self.layoutWidget)
        self.jq_danzhi_text.setObjectName("jq_danzhi_text")
        self.gridLayout.addWidget(self.jq_danzhi_text, 6, 0, 1, 1)
        self.jq_danzhi_lbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.jq_danzhi_lbar.setProperty("value", 0)
        self.jq_danzhi_lbar.setTextVisible(False)
        self.jq_danzhi_lbar.setObjectName("jq_danzhi_lbar")
        self.gridLayout.addWidget(self.jq_danzhi_lbar, 6, 1, 1, 1)
        self.jq_danzhi_lnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.jq_danzhi_lnum.setProperty("value", 0.00)
        self.jq_danzhi_lnum.setObjectName("jq_danzhi_lnum")
        self.gridLayout.addWidget(self.jq_danzhi_lnum, 6, 2, 1, 1)
        self.jq_danzhi_rbar = QtWidgets.QProgressBar(self.layoutWidget)
        self.jq_danzhi_rbar.setProperty("value", 0)
        self.jq_danzhi_rbar.setTextVisible(False)
        self.jq_danzhi_rbar.setObjectName("jq_danzhi_rbar")
        self.gridLayout.addWidget(self.jq_danzhi_rbar, 6, 3, 1, 1)
        self.jq_danzhi_rnum = QtWidgets.QLCDNumber(self.layoutWidget)
        self.jq_danzhi_rnum.setProperty("value", 0.00)
        self.jq_danzhi_rnum.setObjectName("jq_danzhi_rnum")
        self.gridLayout.addWidget(self.jq_danzhi_rnum, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image.setText(_translate("MainWindow", "显示窗口"))
        self.groupBox.setTitle(_translate("MainWindow", "设置"))
        self.scene_select.setItemText(0, _translate("MainWindow", "对接线缆"))
        self.scene_select.setItemText(1, _translate("MainWindow", "器件切割、打孔等"))
        self.scene_select.setItemText(2, _translate("MainWindow", "使用移液枪"))
        self.scene_select.setItemText(3, _translate("MainWindow", "使用移液枪（有精度要求）"))
        self.scene_select.setItemText(4, _translate("MainWindow", "使用胶枪（大）"))
        self.scene_select.setItemText(5, _translate("MainWindow", "使用胶枪（小）"))
        self.scene_text.setText(_translate("MainWindow", "工作场景"))
        self.show_skeleton.setText(_translate("MainWindow", "显示骨骼"))
        self.show_box.setText(_translate("MainWindow", "显示边框"))
        # self.icon.setText(_translate("MainWindow", "TextLabel"))
        self.icon_text.setText(_translate("MainWindow", "未知动作"))
        self.left_pose.setText(_translate("MainWindow", "左手动作：未定义"))
        self.right_pose.setText(_translate("MainWindow", "右手动作：未定义"))
        self.duijie_text.setText(_translate("MainWindow", "手持线缆"))
        self.fuzhe_text.setText(_translate("MainWindow", "扶/按压"))
        self.yyq_chuizhi_text.setText(_translate("MainWindow", "移液枪（垂直）"))
        self.yyq_qingxie_text.setText(_translate("MainWindow", "移液枪（倾斜）"))
        self.jq_sizhi_text.setText(_translate("MainWindow", "胶枪（大）"))
        self.jq_danzhi_text.setText(_translate("MainWindow", "胶枪（小）"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    with open('qss/MaterialDark.qss') as file:
        str = file.readlines()
        str = ''.join(str).strip('\n')
        app.setStyleSheet(str)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
